name: Release

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*.*.*

jobs:
  release:
    env:
      # PORT: 8080
      RUN_SCHEDULED_SEARCHES: false
      MOCK_EXTRACTION: true
      MOCK_NOTIFICATION: true
      DB_TYPE: sqlite
      DB_DATABASE: gpm-test.db
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      # - run: yarn
      # - run: yarn build
      # - run: yarn lint
      # - run: yarn test
      # - run: yarn test:e2e
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/torvi
            ls
            whoami
            git pull
            /home/ubuntu/.nvm/versions/node/v18.12.1/bin/yarn
            /home/ubuntu/.nvm/versions/node/v18.12.1/bin/yarn build
            pm2 restart 0
