name: Release

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*.*.*

jobs:
  release:
    env:
      PORT: 8080
      RUN_SCHEDULED_SEARCHES: false
      MOCK_EXTRACTION: true
      MOCK_NOTIFICATION: true
      DB_TYPE: sqlite
      DB_DATABASE: gpm-test.db
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - run: yarn test:e2e
